# Generated by Django 3.2 on 2021-05-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviment',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
