# Generated by Django 3.2 on 2021-05-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviments', '0002_moviment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviment',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
